version: '3'

services:
  mqtt_borker:
    image: eclipse-mosquitto
    container_name: mosquitto
    ports:
      - 1883:1883
    
  rabbitmq:
    image: rabbitmq:3.6-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=123456
      - RABBITMQ_MANAGEMENT_DEFAULT_USER=rabbitmq
      - RABBITMQ_MANAGEMENT_DEFAULT_PASS=123456